### ISSUE TITLE
Event creation does not take holidays into account

### ISSUE THREAD

**Issue by blhough** [acollins1212/sb2cal#5]
Lectures and Discussion events should be checked against the UCD Holidays before being added.

https://registrar.ucdavis.edu/calendar/holidays.cfm

**Comment by acollins1212** [comment]
Thanks for the heads up! It seems like I'll just have to hard code exceptions when making the Calendar API call. That will be accomplished by Spring Quarter

**Comment by acollins1212** [comment]
Ok, so creating exceptions in a recurring event is not working for me.
I'm following RFC 5545, and I'm putting a test exception in the recurrence array as "EXDATE:20170405T080100Z". It still puts an event on that day (April 5th)...

**Comment by acollins1212** [comment]
@blhough Do you have any experience with exceptions in calendar events in JSON or anything similar? Any help would be very appreciated!

**Comment by blhough** [comment]
Sorry don't know anything about the calendar API. Glad you figured it out though 👍
